<?php

/***************************************
 *
 * Get from STDIN
 *
 **************************************/
echo 'JIRA username: ';
$username = escapeshellcmd(trim(fgets(STDIN)));

echo 'JIRA password: ';
system('stty -echo');
$password = escapeshellcmd(trim(fgets(STDIN)));
system('stty echo');
echo "\n";

echo 'Please input behat tags: ';
$raw_tags = trim(fgets(STDIN));

/***************************************
 *
 * Tags as behat input
 *
 **************************************/

$tags = preg_split("/[, ]+/", $raw_tags);
$cs_tags = implode(",", $tags);
$behat_tags = ' --tags=' . $cs_tags;

/***************************************
 *
 * Temp file as behat input
 *
 **************************************/

$outfile = 'temporary-file-log.tmp';
$behat_outfile = ' --out=' . $outfile;

/***************************************
 *
 * Execute behat
 *
 **************************************/

$behat = '~/behat/vendor/bin/behat --config ~/behat/behat.yml --no-colors --format=pretty' . $behat_outfile . $behat_tags;

exec($behat);

/***************************************
 *
 * Create post.json
 *
 **************************************/

$test_results = file_get_contents($outfile);

$today = date('Y-m-d');
$now = date('H:i:sa');

$key = 'DRUP';
$summary = 'TEST RESULTS: ' . $today . ' ' . $now;
$description = "These are test results generated by the Behat/Mink framework. Please check below for more information.\n\nDATE: " . $today . "\nTIME: " . $now . "\nTAGS: " . $raw_tags . "\nRAW RESULTS:\n" . $test_results;
$id = '1';
$name = 'lli';

$post_object = array(
    'fields' => array(
        'project' => array(
            'key' => $key
        ),
        'summary' => $summary,
        'description' => $description,
        'issuetype' => array(
            'id' => $id
        ),
        'assignee' => array(
            'name' => $name
        )
    )
);

$post_json = 'post.json';
$post_json_fd = fopen($post_json, 'w+');
fwrite($post_json_fd, json_encode($post_object));

/***************************************
 *
 * Post resuts onto JIRA
 *
 **************************************/

$post_php = 'php post.php ' . $post_json . ' ' . $username . ' ' . $password;
exec($post_php);

/***************************************
 *
 * Clean up
 *
 **************************************/

unlink($outfile);
unlink($post_json);

?>
